# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # Các phiên bản Node.js cần kiểm tra

    steps:
      # Checkout code từ repository
      - uses: actions/checkout@v4

      # Thiết lập môi trường Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # Cài đặt dependencies
      - name: Install dependencies
        run: yarn install

      # Build ứng dụng
      - name: Build application
        run: yarn build
